pipleine{
	agent any
	
	stages{
		stage('Check stage'){
		steps{
			withMaven(maven: 'Mvn'){
			bat 'Mvn --versio'
		}{
	}
	
		stage('Compile stage'){
		steps{
			withMaven(maven: 'Mvn'){
		
			bat 'Mvn clean compile'
		}
	}
	
		stage('Test stage'){
		steps{
			withMaven(maven: 'Mvn'){
			bat 'mvn test'
		}
	}
	}
}