pipeline{

agent any

stages{
stage('Check Stage'){
steps{
withMaven(maven : 'Mvn'){
bat 'mvn --version'
}
}
}
stage('Compile Stage'){
steps{
withMaven(maven : 'Mvn'){
bat 'mvn -f mvn-bank/pom.xml compile'
}
}
}
stage('Test Stage'){
steps{
withMaven(maven : 'Mvn'){
bat 'mvn -f mvn-bank/pom.xml install'
}
}
}
}
}